services:
  node:
    build: ./app
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: ${ENVIRONMENT}
      HOST: ${HOST}
      PORT: ${PORT}
    volumes:
      - snpmsg-node-modules:/app/node_modules

volumes:
  snpmsg-node-modules:
